# Generated by Django 4.1.6 on 2023-02-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='github',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='linkedin',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
